# 球队中文名映射表（英文 → 中文）
TEAM_CN_MAP = {
    "Algeria": "阿尔及利亚",
    "Argentina": "阿根廷",
    "Australia": "澳大利亚",
    "Austria": "奥地利",
    "Belgium": "比利时",
    "Bosnia & Herzegovina": "波黑",
    "Brazil": "巴西",
    "Cameroon": "喀麦隆",
    "Canada": "加拿大",
    "Cape Verde": "佛得角",
    "Cape Verde Islands": "佛得角",
    "Chile": "智利",
    "China": "中国",
    "Colombia": "哥伦比亚",
    "Congo DR": "刚果金",
    "Costa Rica": "哥斯达黎加",
    "Croatia": "克罗地亚",
    "Curaçao": "库拉索",
    "Czech Republic": "捷克",
    "Czechia": "捷克",
    "Denmark": "丹麦",
    "DR Congo": "刚果金",
    "Ecuador": "厄瓜多尔",
    "Egypt": "埃及",
    "England": "英格兰",
    "Finland": "芬兰",
    "France": "法国",
    "Germany": "德国",
    "Ghana": "加纳",
    "Greece": "希腊",
    "Haiti": "海地",
    "Hungary": "匈牙利",
    "Iceland": "冰岛",
    "Iran": "伊朗",
    "Iraq": "伊拉克",
    "Israel": "以色列",
    "Italy": "意大利",
    "Ivory Coast": "科特迪瓦",
    "Jamaica": "牙买加",
    "Japan": "日本",
    "Jordan": "约旦",
    "Kazakhstan": "哈萨克斯坦",
    "Kenya": "肯尼亚",
    "Kuwait": "科威特",
    "Mexico": "墨西哥",
    "Morocco": "摩洛哥",
    "Netherlands": "荷兰",
    "New Zealand": "新西兰",
    "Nigeria": "尼日利亚",
    "North Korea": "朝鲜",
    "North Macedonia": "北马其顿",
    "Northern Ireland": "北爱尔兰",
    "Norway": "挪威",
    "Panama": "巴拿马",
    "Paraguay": "巴拉圭",
    "Peru": "秘鲁",
    "Poland": "波兰",
    "Portugal": "葡萄牙",
    "Qatar": "卡塔尔",
    "Republic of Ireland": "爱尔兰",
    "Romania": "罗马尼亚",
    "Russia": "俄罗斯",
    "Saudi Arabia": "沙特阿拉伯",
    "Scotland": "苏格兰",
    "Senegal": "塞内加尔",
    "Serbia": "塞尔维亚",
    "Slovakia": "斯洛伐克",
    "Slovenia": "斯洛文尼亚",
    "South Africa": "南非",
    "South Korea": "韩国",
    "Spain": "西班牙",
    "Sweden": "瑞典",
    "Switzerland": "瑞士",
    "Tunisia": "突尼斯",
    "Turkey": "土耳其",
    "Türkiye": "土耳其",
    "USA": "美国",
    "Ukraine": "乌克兰",
    "United Arab Emirates": "阿联酋",
    "Uruguay": "乌拉圭",
    "Uzbekistan": "乌兹别克斯坦",
    "Venezuela": "委内瑞拉",
    "Wales": "威尔士",
    "Zambia": "赞比亚",
}
